apiVersion: v1
kind: Pod 
metadata:
  name: multi-pod-2
  labels:  
    type: multicontainer
    author: sonal 
spec:
  containers:
    - name: c1
      image: ubuntu 
      command: ["bash", "-c", "sleep 6000"] 
    - name: c2
      image: httpd
    - name: c3
      image: tomcat 
