apiVersion: v1
kind: Pod 
metadata:
  name: test-pod
  labels:  
    type: webserver
    author: sonal 
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["bash", "-c", "sleep 6000"]
