apiVersion: v1
kind: Pod 
metadata:
  name: multi-pod
  labels:  
    type: multicontainer
    author: sonal 
spec:
  containers:
    - name: c1
      image: ubuntu  
    - name: c2
      image: httpd
    - name: c3
      image: nginx 
