apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
  labels:
    app: pvc
spec:
 containers:
   - name: c1
     image: nginx
     volumeMounts:
       - mountPath: "/data"
         name: my-volume
 volumes:
  - name: my-volume
    persistentVolumeClaim:
     claimName: pvc
