apiVersion: batch/v1

kind: Job

metadata:

  name: job1

spec:
 completions: 4
 parallelism: 3
 backoffLimit: 2
 ttlSecondsAfterFinished: 60 
 template:

   spec:

    containers:

      - name: c1

        image: perl:5.34.0

        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
    restartPolicy: Never
