apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mydeploy
spec:
 replicas: 3
 minReadySeconds: 10
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1  # old pod deleted in old replicaset
     maxSurge: 1   # new pod created in new replicaset 
 selector:
  matchLabels:
    app: webserver
 template:
  metadata:
   labels:
     app: webserver
  spec:
   - name: c1
     image: leaddevops/kubeserve:v1
---
apiVersion: v1
kind: Service 
metadata:
  name: mysvc 
spec: 
 type: NodePort 
 ports:
   - port: 80
     targetPort: 80
 selector:
   app: webserver
